wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717619758
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      - 50
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      - 50
      - 55
      - 105
      3:
      - 23
      4: 3.11.2
      5: 0.17.0
      6: 4.41.0
      8:
      - 5
      13: linux-x86_64
