defaults:
  - foundation: octo-base

task: ${.foundation.task}  # relative to the foundation
bonus: False
kind: sb3
downscale: 7
device: null

obs_keys: # anything besides the expected image
  - agent_qpos
  - agent_qvel
  - agent_partial-action
  - simpler-img
  - obj-wrt-eef

goal:
  use: True
  key: simpler-img
  cls: ${r_typeof:improve.wrapper.GoalEnvWrapper}

residual_scale: 1
use_original_space: ${algo.use_original_space}
# should add foundation_key: agent_partial-action ?
use_wandb: ${job.wandb.use}

seed:
  force: False
  value: ${job.seed}

reward: sparse
