defaults:
  - foundation: octo-base
  - obs_mode: image
  
task: ${.foundation.task}  # relative to the foundation
bonus: False
kind: sb3
downscale: 7
device: null

# anything besides the expected image
obs_keys: ${env.obs_mode.obs_keys}

goal:
  use: True
  key: simpler-img
  cls: ${r_typeof:improve.wrapper.GoalEnvWrapper}

residual_scale: 1
action_mask_dims: null
use_original_space: ${algo.use_original_space}
# should add foundation_key: agent_partial-action ?
use_wandb: ${job.wandb.use}

seed:
  force: False
  value: ${job.seed}
  seeds: null

reward: sparse
max_episode_steps: 60
n_envs: 16
no_quarternion: False
reach: False # use reach task?
