name: "sac"

policy_kwargs:
  share_features_extractor: True

learning_rate: ${r_tofloat:3e-4}

# 1m samples was too many (858GB) for 24GB.
buffer_size: ${buffer.size} 
# 120 * 50 epiisodes = 6000 steps
learning_starts: ${r_toint:1e3} # n env steps to collect transitions for before learning 

batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
action_noise: null

# replay_buffer: ${.buffer._target_}
replay_buffer_class: ${buffer.cls}
replay_buffer_kwargs: ${buffer.args}
optimize_memory_usage: false

ent_coef: auto_0.05
# target_entropy: 'auto'

target_update_interval: 1
use_sde: false
sde_sample_freq: -1
use_sde_at_warmup: false

stats_window_size: 10 # was 100 ... for logging only
tensorboard_log: null
seed: 0
device: 'auto'
_init_setup_model: true

use_original_space: False
warmup_zero_action: False
