# @package _global_

# help with sweepers
# https://stackoverflow.com/questions/70619014/specify-hydra-multirun-sweeps-in-a-config-file
# https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1011704938

defaults:
# - /launcher: base
  - override /algo: sac
  - override /buffer: base
  - override /env/foundation: dont

  - _self_

log_dir: ${callback.log_path}
sweep_id: "jun10_basics_dist"

train: 
  n_steps: ${r_toint:3e5} # 300k
  use_zero_init: False # cant zero without foundation model

algo:
  buffer_size: ${r_toint:1e6}
  warmup_zero_action: False # gaussian
  batch_size: 256
  learning_starts: ${r_toint:1e4}

env:
  goal: 
    use: False
  seed:
    force: True

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

  mode: MULTIRUN # needed or else -m flag
  sweeper:
    params:
      algo.learning_rate: ${r_tofloat:3e-4},${r_tofloat:1e-4},${r_tofloat:1e-3}
      algo.ent_coef: auto_0.5,auto_1
      algo.use_sde: False,True
      algo.target_update_interval: 1,5,10
