# @package _global_

# to see if sac works at certain batch size and buffer size

# help with sweepers
# https://stackoverflow.com/questions/70619014/specify-hydra-multirun-sweeps-in-a-config-file
# https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1011704938

defaults:
  - override /env: base
  - override /algo: sac
  - override /job: base
  - override /train: base
  - override /callback: base

  - _self_

log_dir: ${callback.log_path}
sweep_id: "may30_sac_downscale_batch256"
train: # has to be nested to override the base train config
  n_steps: ${r_toint:2e6} # only 20k steps to get a feel
algo:
  batch_size: 256

env:
  downscale: 3 # 3 in both w h dimensions is 9 ... final (213,160)

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

  sweeper:
    params: 
      +algo: "{learning_starts:10000,buffer_size:10000}"
