# @package _global_
defaults:
  - override /hydra/launcher: submitit_local
  - _self_

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 180
    cpus_per_task: null
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: null
    nodes: 8
    name: ${hydra.job.name}

